### ISSUE TITLE
it is posible to fix my problem, that happened while importing the first asset from snipe  

### ISSUE THREAD

**Issue by Salise05** [derlucas/snipeit-netbox#2]
Traceback (most recent call last):
  File "/home/netboxuser/main.py", line 40, in <module>
    syncer.sync_assets_to_devices(assets)
  File "/home/netboxuser/syncer.py", line 415, in sync_assets_to_devices
    self.__sync_device(nb_device_type, nb_tenant, netbox_devices, role, site, snipe_asset)
  File "/home/netboxuser/syncer.py", line 486, in __sync_device
    self.__update_device(device, snipe_asset, nb_role, nb_site, nb_tenant, nb_device_type, False)
  File "/home/netboxuser/syncer.py", line 437, in __update_device
    if nb_device['device_role']['id'] != nb_role['id']:
       ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/netboxuser/venv/lib/python3.11/site-packages/pynetbox/core/response.py", line 323, in __getitem__
    return dict(self)[k]
           ~~~~~~~~~~^^^
KeyError: 'device_role'

**Comment by Salise05** [comment]
Perfect thanks to you, the update has helped, I no longer get an error message
