### ISSUE TITLE
The request failed with code 400 Bad Request

### ISSUE THREAD

**Issue by jennso** [derlucas/snipeit-netbox#3]
Fresh instance of snipeit version 7.0.11 and netbox NetBox Community v4.1.0 and Python 3.11.5, I only have 1 asset in snipeit to test I'm also using https on both endpoints, connection to the api seems to be ok once I export REQUESTS_CA_BUNDLE= pointing to my bundle ca.

Looks like it fails to create the custom field on netbox.

```
INFO:root:Checking Netbox Custom Fields
INFO:root:netbox custom field is missing -> creating one
Traceback (most recent call last):
  File "/root/snipeit-netbox/main.py", line 28, in <module>
    syncer.ensure_netbox_custom_field(False)
  File "/root/snipeit-netbox/syncer.py", line 72, in ensure_netbox_custom_field
    self.netbox.extras.custom_fields.create(cufi)
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/endpoint.py", line 415, in create
    ).post(args[0] if args else kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/query.py", line 357, in post
    return self._make_call(verb="post", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pynetbox/core/query.py", line 247, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'object_types': ['This field is required.']}
```

**Comment by derlucas** [comment]
Thanks to @tylerc for fixing this. I currently have not much free time to work on this. But i'm planning on developing this further.

**Comment by jennso** [comment]
I had also fixed it on my side, I was about to ask for a pull rquest, thank you for the fix!
